services:
  redis:
    container_name: redis_dfl
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    networks:
      - dfl
    restart: always

  mongo:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    networks:
      - dfl
    restart: always

#  reception-orders:
#    container_name: reception-orders
#    build: ./
#    ports:
#      - ${NEST_PORT_APP}:3000
#    environment:
#      - NEST_PORT_APP=3000
#    command: npm run star:dev
#    networks:
#      - dfl
#    depends_on:
#      - mongo

networks:
  dfl:
    driver: bridge

volumes:
  redis:
    driver: local
  mongo: { }
